package Project_Euler_Solutions_in_Java._01_31;

import Project_Euler_Solutions_in_Java.Utils.Util;

public class _002_even_fibonacci {
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 */
	public static void main(String[] args) {
		Util.println(new _002_even_fibonacci().run());
	}
	public int run(){
		int four_mill = 4000000;
		int answer = 0;
		for(int a = 1, b = 2, temp; b < four_mill; temp = a+b, a = b, b = temp){
			answer += Util.isIntMultiple(b, 2) ? b : 0;
		}
		return answer;
	}
}
